#!/bin/bash

X11_SOCKET=/tmp/.X11-unix
PA_SOCKET=/tmp/pulseaudio.socket
FONTS=/usr/share/fonts

# 安装xhost管理X server连接权限
if ! hash xhost; then
        echo "install xhost ..."
        sudo zypper install xhost
fi

# 对所有用户开放
if [[ "$(xhost)" =~ "enabled" ]]; then
        xhost +
fi

# 生成pulseaudio socket
# $ pacmd describe-module module-native-protocol-unix
if [ ! -S $PA_SOCKET ] || [ ! -f $PA_COOKIE ]; then
	pacmd load-module module-native-protocol-unix \
		socket=$PA_SOCKET \
		auth-anonymous=1
fi

podman run -it \
	--network=host \
	-e DISPLAY=$DISPLAY \
	-v $X11_SOCKET:$X11_SOCKET:ro \
	-v $PA_SOCKET:$PA_SOCKET:ro \
	-v $FONTS:$FONTS:ro \
	--device /dev/dri \
	--device /dev/vga_arbiter \
	--device /dev/snd \
	--rm \
	chromium-with-proxy \
	"$1"
